
---
- hosts: all
  become: true
  gather_facts: false

  tasks:

  - name: Get host info
    community.docker.docker_host_info:
      containers: yes
      images: yes
    register: docker_info

  - name: Remove all containers and their volumes
    community.docker.docker_container:
      name: "{{ item }}"
      state: absent
      keep_volumes: no
    loop: "{{ docker_info.containers | map(attribute='Id') }}"

  - name: Remove all images
    community.docker.docker_image:
      name: "{{ item }}"
      state: absent
      force_absent: yes
    loop: "{{ docker_info.images | map(attribute='Id') }}"